"""add_user_preferences_table

Revision ID: 52e2b2a85aec
Revises: da44f6d378a1
Create Date: 2026-01-04 11:20:14.517587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52e2b2a85aec'
down_revision: Union[str, Sequence[str], None] = 'da44f6d378a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('api_key_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_sessions_api_key_hash'), 'sessions', ['api_key_hash'], unique=False)
    op.create_index('ix_sessions_expires_at', 'sessions', ['expires_at'], unique=False)
    op.create_index('ix_sessions_user_api_key', 'sessions', ['user_id', 'api_key_hash'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('user_preferences',
    sa.Column('preference_id', sa.String(length=36), nullable=False, comment='UUID primary key (Python-generated)'),
    sa.Column('user_id', sa.String(length=255), nullable=False, comment='User identifier (from X-VERITTA-USER-ID header)'),
    sa.Column('tone_preference', sa.String(length=50), nullable=True, comment='Tone: institutional|technical|conversational'),
    sa.Column('output_format', sa.String(length=50), nullable=True, comment='Format: text|bullet_points|checklist|table|structured'),
    sa.Column('language', sa.String(length=10), nullable=True, comment='Language: pt-BR|en-US'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Last update timestamp (UTC)'),
    sa.PrimaryKeyConstraint('preference_id')
    )
    op.create_index(op.f('ix_user_preferences_user_id'), 'user_preferences', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_preferences_user_id'), table_name='user_preferences')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index('ix_sessions_user_api_key', table_name='sessions')
    op.drop_index('ix_sessions_expires_at', table_name='sessions')
    op.drop_index(op.f('ix_sessions_api_key_hash'), table_name='sessions')
    op.drop_table('sessions')
    # ### end Alembic commands ###
